users:
  roberto:
    username: roberto
    articleIds:
      - 1
      - 2
    commentIds: []
  jack frost:
    username: jack frost
    articleIds: []
    commentIds:
      - 1
  chester:
    username: chester
    articleIds: []
    commentIds:
      - 2
  fran:
    username: fran
    articleIds: []
    commentIds: []
  flippy:
    username: flippy
    articleIds:
      - 3
    commentIds: []
articles:
  '1':
    id: 1
    title: This guy is a dick
    url: 'https://www.cnn.com/2018/02/03/politics/donald-trump-memo/index.html'
    username: roberto
    commentIds:
      - 2
    upvotedBy: []
    downvotedBy: []
    comments: []
  '2':
    id: 2
    title: This one too
    url: >-
      http://abcnews.go.com/Politics/pence-visit-pennsylvania-gop-stronghold-targeted-democrats-special/story?id=52784865
    username: roberto
    commentIds:
      - 1
    upvotedBy: []
    downvotedBy: []
    comments:
      - &ref_0
        id: 1
        body: bigger dick than the other one
        articleId: 2
        username: jack frost
        upvotedBy:
          - jack frost
        downvotedBy: []
  '3':
    id: 3
    title: Birds of a Feather
    url: >-
      https://www.huffingtonpost.com/entry/sean-hannity-pee-tape_us_5a73f69de4b0905433b2ba6d
    username: flippy
    commentIds: []
    upvotedBy: []
    downvotedBy: []
nextArticleId: 4
comments:
  '1': *ref_0
  '2':
    id: 2
    body: greatest ever - your stoopider
    articleId: 1
    username: chester
    upvotedBy:
      - chester
      - fran
    downvotedBy: []
nextCommentId: 3
